export const countries = [
  { id: 1, label: 'Afghanistan', value: 'af' },
  { id: 2, label: 'Albania', value: 'al' },
  { id: 3, label: 'Algeria', value: 'dz' },
  { id: 4, label: 'American Samoa', value: 'as' },
  { id: 5, label: 'Andorra', value: 'ad' },
  { id: 6, label: 'Angola', value: 'ao' },
  { id: 7, label: 'Anguilla', value: 'ai' },
  { id: 8, label: 'Antarctica', value: 'aq' },
  { id: 9, label: 'Antigua and Barbuda', value: 'ag' },
  { id: 10, label: 'Argentina', value: 'ar' },
  { id: 11, label: 'Armenia', value: 'am' },
  { id: 12, label: 'Aruba', value: 'aw' },
  { id: 13, label: 'Australia', value: 'au' },
  { id: 14, label: 'Austria', value: 'at' },
  { id: 15, label: 'Azerbaijan', value: 'az' },
  { id: 16, label: 'Bahamas', value: 'bs' },
  { id: 17, label: 'Bahrain', value: 'bh' },
  { id: 18, label: 'Bangladesh', value: 'bd' },
  { id: 19, label: 'Barbados', value: 'bb' },
  { id: 20, label: 'Belarus', value: 'by' },
  { id: 21, label: 'Belgium', value: 'be' },
  { id: 22, label: 'Belize', value: 'bz' },
  { id: 23, label: 'Benin', value: 'bj' },
  { id: 24, label: 'Bermuda', value: 'bm' },
  { id: 25, label: 'Bhutan', value: 'bt' },
  { id: 26, label: 'Bolivia', value: 'bo' },
  { id: 27, label: 'Bosnia and Herzegovina', value: 'ba' },
  { id: 28, label: 'Botswana', value: 'bw' },
  { id: 29, label: 'Bouvet Island', value: 'bv' },
  { id: 30, label: 'Brazil', value: 'br' },
  { id: 31, label: 'British Indian Ocean Territory', value: 'io' },
  { id: 32, label: 'British Virgin Islands', value: 'vg' },
  { id: 33, label: 'Brunei', value: 'bn' },
  { id: 34, label: 'Bulgaria', value: 'bg' },
  { id: 35, label: 'Burkina Faso', value: 'bf' },
  { id: 36, label: 'Burundi', value: 'bi' },
  { id: 37, label: 'Cabo Verde', value: 'cv' },
  { id: 38, label: 'Cambodia', value: 'kh' },
  { id: 39, label: 'Cameroon', value: 'cm' },
  { id: 40, label: 'Canada', value: 'ca' },
  { id: 41, label: 'Caribbean Netherlands', value: 'bq' },
  { id: 42, label: 'Cayman Islands', value: 'ky' },
  { id: 43, label: 'Central African Republic', value: 'cf' },
  { id: 44, label: 'Chad', value: 'td' },
  { id: 45, label: 'Chile', value: 'cl' },
  { id: 46, label: 'China', value: 'cn' },
  { id: 47, label: 'Christmas Island', value: 'cx' },
  { id: 48, label: 'Cocos (Keeling) Islands', value: 'cc' },
  { id: 49, label: 'Colombia', value: 'co' },
  { id: 50, label: 'Comoros', value: 'km' },
  { id: 51, label: 'Cook Islands', value: 'ck' },
  { id: 52, label: 'Costa Rica', value: 'cr' },
  { id: 53, label: 'Croatia', value: 'hr' },
  { id: 54, label: 'Cuba', value: 'cu' },
  { id: 55, label: 'Curaçao', value: 'cw' },
  { id: 56, label: 'Cyprus', value: 'cy' },
  { id: 57, label: 'Czechia', value: 'cz' },
  { id: 58, label: "Côte d'Ivoire", value: 'ci' },
  { id: 59, label: 'Democratic Republic of the Congo', value: 'cd' },
  { id: 60, label: 'Denmark', value: 'dk' },
  { id: 61, label: 'Djibouti', value: 'dj' },
  { id: 62, label: 'Dominica', value: 'dm' },
  { id: 63, label: 'Dominican Republic', value: 'do' },
  { id: 64, label: 'Ecuador', value: 'ec' },
  { id: 65, label: 'Egypt', value: 'eg' },
  { id: 66, label: 'El Salvador', value: 'sv' },
  { id: 67, label: 'Equatorial Guinea', value: 'gq' },
  { id: 68, label: 'Eritrea', value: 'er' },
  { id: 69, label: 'Estonia', value: 'ee' },
  { id: 70, label: 'Eswatini', value: 'sz' },
  { id: 71, label: 'Ethiopia', value: 'et' },
  { id: 72, label: 'Falkland Islands', value: 'fk' },
  { id: 73, label: 'Faroe Islands', value: 'fo' },
  { id: 74, label: 'Fiji', value: 'fj' },
  { id: 75, label: 'Finland', value: 'fi' },
  { id: 76, label: 'France', value: 'fr' },
  { id: 77, label: 'French Guiana', value: 'gf' },
  { id: 78, label: 'French Polynesia', value: 'pf' },
  { id: 79, label: 'French Southern Territories', value: 'tf' },
  { id: 80, label: 'Gabon', value: 'ga' },
  { id: 81, label: 'Gambia', value: 'gm' },
  { id: 82, label: 'Georgia', value: 'ge' },
  { id: 83, label: 'Germany', value: 'de' },
  { id: 84, label: 'Ghana', value: 'gh' },
  { id: 85, label: 'Gibraltar', value: 'gi' },
  { id: 86, label: 'Greece', value: 'gr' },
  { id: 87, label: 'Greenland', value: 'gl' },
  { id: 88, label: 'Grenada', value: 'gd' },
  { id: 89, label: 'Guadeloupe', value: 'gp' },
  { id: 90, label: 'Guam', value: 'gu' },
  { id: 91, label: 'Guatemala', value: 'gt' },
  { id: 92, label: 'Guernsey', value: 'gg' },
  { id: 93, label: 'Guinea', value: 'gn' },
  { id: 94, label: 'Guinea-Bissau', value: 'gw' },
  { id: 95, label: 'Guyana', value: 'gy' },
  { id: 96, label: 'Haiti', value: 'ht' },
  { id: 97, label: 'Heard Island and McDonald Islands', value: 'hm' },
  { id: 98, label: 'Honduras', value: 'hn' },
  { id: 99, label: 'Hong Kong', value: 'hk' },
  { id: 100, label: 'Hungary', value: 'hu' },
  { id: 101, label: 'Iceland', value: 'is' },
  { id: 102, label: 'India', value: 'in' },
  { id: 103, label: 'Indonesia', value: 'id' },
  { id: 104, label: 'Iran', value: 'ir' },
  { id: 105, label: 'Iraq', value: 'iq' },
  { id: 106, label: 'Ireland', value: 'ie' },
  { id: 107, label: 'Isle of Man', value: 'im' },
  { id: 108, label: 'Israel', value: 'il' },
  { id: 109, label: 'Italy', value: 'it' },
  { id: 110, label: 'Jamaica', value: 'jm' },
  { id: 111, label: 'Japan', value: 'jp' },
  { id: 112, label: 'Jersey', value: 'je' },
  { id: 113, label: 'Jordan', value: 'jo' },
  { id: 114, label: 'Kazakhstan', value: 'kz' },
  { id: 115, label: 'Kenya', value: 'ke' },
  { id: 116, label: 'Kiribati', value: 'ki' },
  { id: 117, label: 'Kosovo', value: 'xk' },
  { id: 118, label: 'Kuwait', value: 'kw' },
  { id: 119, label: 'Kyrgyzstan', value: 'kg' },
  { id: 120, label: 'Laos', value: 'la' },
  { id: 121, label: 'Latvia', value: 'lv' },
  { id: 122, label: 'Lebanon', value: 'lb' },
  { id: 123, label: 'Lesotho', value: 'ls' },
  { id: 124, label: 'Liberia', value: 'lr' },
  { id: 125, label: 'Libya', value: 'ly' },
  { id: 126, label: 'Liechtenstein', value: 'li' },
  { id: 127, label: 'Lithuania', value: 'lt' },
  { id: 128, label: 'Luxembourg', value: 'lu' },
  { id: 129, label: 'Macao', value: 'mo' },
  { id: 130, label: 'Madagascar', value: 'mg' },
  { id: 131, label: 'Malawi', value: 'mw' },
  { id: 132, label: 'Malaysia', value: 'my' },
  { id: 133, label: 'Maldives', value: 'mv' },
  { id: 134, label: 'Mali', value: 'ml' },
  { id: 135, label: 'Malta', value: 'mt' },
  { id: 136, label: 'Marshall Islands', value: 'mh' },
  { id: 137, label: 'Martinique', value: 'mq' },
  { id: 138, label: 'Mauritania', value: 'mr' },
  { id: 139, label: 'Mauritius', value: 'mu' },
  { id: 140, label: 'Mayotte', value: 'yt' },
  { id: 141, label: 'Mexico', value: 'mx' },
  { id: 142, label: 'Micronesia', value: 'fm' },
  { id: 143, label: 'Moldova', value: 'md' },
  { id: 144, label: 'Monaco', value: 'mc' },
  { id: 145, label: 'Mongolia', value: 'mn' },
  { id: 146, label: 'Montenegro', value: 'me' },
  { id: 147, label: 'Montserrat', value: 'ms' },
  { id: 148, label: 'Morocco', value: 'ma' },
  { id: 149, label: 'Mozambique', value: 'mz' },
  { id: 150, label: 'Myanmar', value: 'mm' },
  { id: 151, label: 'Namibia', value: 'na' },
  { id: 152, label: 'Nauru', value: 'nr' },
  { id: 153, label: 'Nepal', value: 'np' },
  { id: 154, label: 'Netherlands', value: 'nl' },
  { id: 155, label: 'New Caledonia', value: 'nc' },
  { id: 156, label: 'New Zealand', value: 'nz' },
  { id: 157, label: 'Nicaragua', value: 'ni' },
  { id: 158, label: 'Niger', value: 'ne' },
  { id: 159, label: 'Nigeria', value: 'ng' },
  { id: 160, label: 'Niue', value: 'nu' },
  { id: 161, label: 'Norfolk Island', value: 'nf' },
  { id: 162, label: 'North Korea', value: 'kp' },
  { id: 163, label: 'North Macedonia', value: 'mk' },
  { id: 164, label: 'Northern Mariana Islands', value: 'mp' },
  { id: 165, label: 'Norway', value: 'no' },
  { id: 166, label: 'Oman', value: 'om' },
  { id: 167, label: 'Pakistan', value: 'pk' },
  { id: 168, label: 'Palau', value: 'pw' },
  { id: 169, label: 'Panama', value: 'pa' },
  { id: 170, label: 'Papua New Guinea', value: 'pg' },
  { id: 171, label: 'Paraguay', value: 'py' },
  { id: 172, label: 'Peru', value: 'pe' },
  { id: 173, label: 'Philippines', value: 'ph' },
  { id: 174, label: 'Pitcairn Islands', value: 'pn' },
  { id: 175, label: 'Poland', value: 'pl' },
  { id: 176, label: 'Portugal', value: 'pt' },
  { id: 177, label: 'Puerto Rico', value: 'pr' },
  { id: 178, label: 'Qatar', value: 'qa' },
  { id: 179, label: 'Republic of the Congo', value: 'cg' },
  { id: 180, label: 'Romania', value: 'ro' },
  { id: 181, label: 'Russia', value: 'ru' },
  { id: 182, label: 'Rwanda', value: 'rw' },
  { id: 183, label: 'Réunion', value: 're' },
  { id: 184, label: 'Saint Barthélemy', value: 'bl' },
  { id: 185, label: 'Saint Helena', value: 'sh' },
  { id: 186, label: 'Saint Kitts and Nevis', value: 'kn' },
  { id: 187, label: 'Saint Lucia', value: 'lc' },
  { id: 188, label: 'Saint Martin', value: 'mf' },
  { id: 189, label: 'Saint Pierre and Miquelon', value: 'pm' },
  { id: 190, label: 'Saint Vincent and the Grenadines', value: 'vc' },
  { id: 191, label: 'Samoa', value: 'ws' },
  { id: 192, label: 'San Marino', value: 'sm' },
  { id: 193, label: 'Saudi Arabia', value: 'sa' },
  { id: 194, label: 'Senegal', value: 'sn' },
  { id: 195, label: 'Serbia', value: 'rs' },
  { id: 196, label: 'Seychelles', value: 'sc' },
  { id: 197, label: 'Sierra Leone', value: 'sl' },
  { id: 198, label: 'Singapore', value: 'sg' },
  { id: 199, label: 'Sint Maarten', value: 'sx' },
  { id: 200, label: 'Slovakia', value: 'sk' },
  { id: 201, label: 'Slovenia', value: 'si' },
  { id: 202, label: 'Solomon Islands', value: 'sb' },
  { id: 203, label: 'Somalia', value: 'so' },
  { id: 204, label: 'South Africa', value: 'za' },
  {
    id: 205,
    label: 'South Georgia and the South Sandwich Islands',
    value: 'gs',
  },
  { id: 206, label: 'South Korea', value: 'kr' },
  { id: 207, label: 'South Sudan', value: 'ss' },
  { id: 208, label: 'Spain', value: 'es' },
  { id: 209, label: 'Sri Lanka', value: 'lk' },
  { id: 210, label: 'Sudan', value: 'sd' },
  { id: 211, label: 'Suriname', value: 'sr' },
  { id: 212, label: 'Svalbard and Jan Mayen', value: 'sj' },
  { id: 213, label: 'Sweden', value: 'se' },
  { id: 214, label: 'Switzerland', value: 'ch' },
  { id: 215, label: 'Syria', value: 'sy' },
  { id: 216, label: 'São Tomé and Príncipe', value: 'st' },
  { id: 217, label: 'Tajikistan', value: 'tj' },
  { id: 218, label: 'Tanzania', value: 'tz' },
  { id: 219, label: 'Thailand', value: 'th' },
  { id: 220, label: 'Timor-Leste', value: 'tl' },
  { id: 221, label: 'Togo', value: 'tg' },
  { id: 222, label: 'Tokelau', value: 'tk' },
  { id: 223, label: 'Tonga', value: 'to' },
  { id: 224, label: 'Trinidad and Tobago', value: 'tt' },
  { id: 225, label: 'Tunisia', value: 'tn' },
  { id: 226, label: 'Turkey', value: 'tr' },
  { id: 227, label: 'Turkmenistan', value: 'tm' },
  { id: 228, label: 'Turks and Caicos Islands', value: 'tc' },
  { id: 229, label: 'Tuvalu', value: 'tv' },
  { id: 230, label: 'U.S. Virgin Islands', value: 'vi' },
  { id: 231, label: 'Uganda', value: 'ug' },
  { id: 232, label: 'Ukraine', value: 'ua' },
  { id: 233, label: 'United Arab Emirates', value: 'ae' },
  { id: 234, label: 'United Kingdom', value: 'gb' },
  { id: 235, label: 'United States', value: 'us' },
  { id: 236, label: 'United States Minor Outlying Islands', value: 'um' },
  { id: 237, label: 'Uruguay', value: 'uy' },
  { id: 238, label: 'Uzbekistan', value: 'uz' },
  { id: 239, label: 'Vanuatu', value: 'vu' },
  { id: 240, label: 'Vatican City', value: 'va' },
  { id: 241, label: 'Venezuela', value: 've' },
  { id: 242, label: 'Vietnam', value: 'vn' },
  { id: 243, label: 'Wallis and Futuna', value: 'wf' },
  { id: 244, label: 'Western Sahara', value: 'eh' },
  { id: 245, label: 'Yemen', value: 'ye' },
  { id: 246, label: 'Zambia', value: 'zm' },
  { id: 247, label: 'Zimbabwe', value: 'zw' },
  { id: 248, label: 'Åland Islands', value: 'ax' },
];
