export const links = {
  user: 'User',
  login: 'User/login',
  signInSocial: 'User/SocialLogin',
  registerWithQuiz: 'User/register-with-quiz',
  analizePhoto: 'Beauty/Analyze-existing-questionnaire',
  analizePhotoAfterRegister: 'Beauty/Analyze',
  beautyProcedure: 'BeautyProcedure',
  editAnalysis: 'Beauty',
  accountAnalyses: 'Beauty/get-account-analyses',
  createPayment: 'Payment/Create-subscription',
  forgotPassword: 'User/forgot-password',
  resetPasssword: 'User/reset-password',
  changePasssword: 'User/change-password',
  changeEmail: 'User/change-email',
  statisticsAverage: 'Statistics/analysisAverage',
  statisticsTop: 'Statistics/topAnalyses',
  statisticsRecent: 'Statistics/recentAnalyses',
  threeCountriesAverage: 'Statistics/country-positions',
  threeUsersAverage: 'Statistics/positions',
  changeSubscription: 'user/set-app-user-id',
  event: 'Event/',
};
